# Generated by Django 4.1.4 on 2023-10-31 23:59

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Advertisements',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50, verbose_name='Тайтл')),
                ('text', models.TextField(verbose_name='Повідомлення')),
                ('time', models.DateTimeField(auto_now_add=True, verbose_name='Час')),
                ('name', models.TextField(verbose_name='Нік користувача')),
            ],
            options={
                'verbose_name': 'Реклама',
                'verbose_name_plural': 'Реклами',
            },
        ),
        migrations.CreateModel(
            name='ChosenProduct',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, verbose_name='Тайтл')),
                ('text', models.TextField(verbose_name='Повідомлення')),
            ],
            options={
                'verbose_name': 'Вибраний продукт',
                'verbose_name_plural': 'Вибрані продукти',
            },
        ),
        migrations.CreateModel(
            name='MainBanner',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='', verbose_name='Фото')),
            ],
            options={
                'verbose_name': 'Головний банер',
                'verbose_name_plural': 'Головні банери',
            },
        ),
        migrations.CreateModel(
            name='UserData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('email', models.CharField(max_length=100)),
                ('time', models.DateTimeField(auto_now_add=True, null=True)),
            ],
        ),
    ]
