# Generated by Django 4.1.4 on 2023-11-01 00:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forum_pages', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userdata',
            name='time',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
