# Generated by Django 4.1.4 on 2023-10-30 20:01

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('forum_pages', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='advertisements',
            options={'verbose_name': 'Реклама', 'verbose_name_plural': 'Реклами'},
        ),
        migrations.AddField(
            model_name='advertisements',
            name='name',
            field=models.TextField(default='', verbose_name='Нік користувача'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='advertisements',
            name='time',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
