# Generated by Django 4.1.4 on 2023-11-15 16:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('forum_pages', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='MainBanner',
            new_name='MainPictureBanner',
        ),
        migrations.RenameModel(
            old_name='ChosenProduct',
            new_name='MainTextBanner',
        ),
    ]
