# Generated by Django 4.1.4 on 2023-11-19 20:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forum_pages', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='mainpicturebanner',
            options={'verbose_name': 'Головний банер зверху', 'verbose_name_plural': 'Головний банер зверху'},
        ),
        migrations.AlterModelOptions(
            name='maintextbanner',
            options={'verbose_name': 'Головний текст зверху', 'verbose_name_plural': 'Головний текст зверху'},
        ),
        migrations.AddField(
            model_name='user',
            name='name',
            field=models.CharField(max_length=100, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='user',
            name='telegram',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='email',
            field=models.EmailField(max_length=254, null=True, unique=True),
        ),
    ]
