# Generated by Django 4.1.4 on 2023-10-30 20:03

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forum_pages', '0002_alter_advertisements_options_advertisements_name_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='advertisements',
            name='time',
            field=models.DateField(default=datetime.date(2023, 10, 30)),
        ),
    ]
