# Generated by Django 4.1.4 on 2023-11-22 19:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forum_pages', '0002_alter_mainpicturebanner_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='avatar',
            field=models.ImageField(default='avatars/default_avatar.png', null=True, upload_to='forum_pages/img/avatars'),
        ),
    ]
