# Generated by Django 4.1.4 on 2023-11-01 00:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forum_pages', '0002_alter_userdata_time'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userdata',
            name='email',
        ),
        migrations.AddField(
            model_name='userdata',
            name='text',
            field=models.TextField(default=''),
            preserve_default=False,
        ),
    ]
