# Generated by Django 4.1.4 on 2023-11-01 00:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('forum_pages', '0003_remove_userdata_email_userdata_text'),
    ]

    operations = [
        migrations.RenameField(
            model_name='userdata',
            old_name='text',
            new_name='main_text',
        ),
    ]
