# Generated by Django 4.2.8 on 2023-12-24 20:25

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('forum_pages', '0003_topagency'),
    ]

    operations = [
        migrations.AddField(
            model_name='topagency',
            name='created',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
