# Generated by Django 4.1.4 on 2023-10-30 20:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forum_pages', '0003_alter_advertisements_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='advertisements',
            name='time',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Час'),
        ),
    ]
