# Generated by Django 4.1.4 on 2023-11-20 20:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forum_pages', '0003_alter_user_telegram'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='avatar',
            field=models.ImageField(default='avatars/default_avatar.png', null=True, upload_to=''),
        ),
    ]
