# Generated by Django 4.1.4 on 2023-11-29 18:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forum_pages', '0004_remove_user_name_alter_user_username'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='is_show_telegram',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='avatar',
            field=models.ImageField(default='forum_pages/img/avatars/default_avatar.png', null=True, upload_to='forum_pages/img/avatars'),
        ),
    ]
