# Generated by Django 4.1.4 on 2023-10-30 20:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forum_pages', '0004_alter_advertisements_time'),
    ]

    operations = [
        migrations.CreateModel(
            name='ChosenProduct',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50, verbose_name='Тайтл')),
                ('text', models.TextField(verbose_name='Повідомлення')),
            ],
            options={
                'verbose_name': 'Вибраний продукт',
                'verbose_name_plural': 'Вибрані продукти',
            },
        ),
        migrations.CreateModel(
            name='MainBanner',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='static/forum_pages/user_img', verbose_name='Фото')),
            ],
            options={
                'verbose_name': 'Головний банер',
                'verbose_name_plural': 'Головні банери',
            },
        ),
    ]
