# Generated by Django 4.2.8 on 2024-01-22 17:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forum_pages', '0004_topagency_created'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='topagency',
            name='banner',
        ),
        migrations.AddField(
            model_name='mainpicturebanner',
            name='detailed_text',
            field=models.TextField(default='', verbose_name='Детальний опис'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='mainpicturebanner',
            name='link',
            field=models.URLField(default=''),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='mainpicturebanner',
            name='title',
            field=models.CharField(default='', max_length=100, verbose_name='Тайтл'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='maintextbanner',
            name='detailed_text',
            field=models.TextField(default='', verbose_name='Детальний опис'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='maintextbanner',
            name='image',
            field=models.ImageField(null=True, upload_to='forum_pages/img/adverts'),
        ),
        migrations.AddField(
            model_name='maintextbanner',
            name='link',
            field=models.URLField(default=''),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='topagency',
            name='detailed_text',
            field=models.TextField(default='', verbose_name='Детальний опис'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='topagency',
            name='image',
            field=models.ImageField(default='', upload_to='forum_pages/img/top_agency'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='topagency',
            name='link',
            field=models.URLField(default=''),
            preserve_default=False,
        ),
    ]
