# Generated by Django 4.1.4 on 2023-10-30 20:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forum_pages', '0005_chosenproduct_mainbanner'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chosenproduct',
            name='title',
            field=models.CharField(max_length=100, verbose_name='Тайтл'),
        ),
        migrations.AlterField(
            model_name='mainbanner',
            name='image',
            field=models.ImageField(upload_to='forum_pages/user_img', verbose_name='Фото'),
        ),
    ]
