# Generated by Django 4.2.8 on 2024-01-22 17:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forum_pages', '0005_remove_topagency_banner_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='topagency',
            name='image',
            field=models.ImageField(null=True, upload_to='forum_pages/img/top_agency'),
        ),
    ]
