# Generated by Django 4.1.4 on 2023-12-03 22:02

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('forum_pages', '0005_user_is_show_telegram_alter_user_avatar'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='themes',
            name='created',
        ),
        migrations.RemoveField(
            model_name='themes',
            name='main_text',
        ),
        migrations.RemoveField(
            model_name='themes',
            name='user',
        ),
        migrations.AlterField(
            model_name='user',
            name='avatar',
            field=models.ImageField(default='forum_pages/img/avatars/default_avatar.png', null=True, upload_to='forum_pages/img/avatars', verbose_name='Фото профілю'),
        ),
        migrations.AlterField(
            model_name='user',
            name='email',
            field=models.EmailField(max_length=254, null=True, unique=True, verbose_name='Ваш E-mail'),
        ),
        migrations.AlterField(
            model_name='user',
            name='is_show_telegram',
            field=models.BooleanField(default=True, verbose_name='Показувати телеграм'),
        ),
        migrations.AlterField(
            model_name='user',
            name='telegram',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='Ваш телеграм нікнейм'),
        ),
        migrations.AlterField(
            model_name='user',
            name='username',
            field=models.CharField(max_length=100, null=True, unique=True, verbose_name='Ваш нікнейм'),
        ),
        migrations.CreateModel(
            name='SubThemes',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, null=True)),
                ('main_text', models.TextField()),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('base_theme', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='forum_pages.themes')),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
