# Generated by Django 4.2.8 on 2024-01-22 18:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forum_pages', '0006_alter_topagency_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='maintextbanner',
            name='image',
            field=models.ImageField(upload_to='forum_pages/img/adverts', verbose_name='Фото'),
        ),
        migrations.AlterField(
            model_name='topagency',
            name='image',
            field=models.ImageField(upload_to='forum_pages/img/top_agency'),
        ),
    ]
