# Generated by Django 4.1.4 on 2023-12-03 22:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('forum_pages', '0006_remove_themes_created_remove_themes_main_text_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='ThemeMessage',
            new_name='SubThemeMessage',
        ),
        migrations.AlterField(
            model_name='subthememessage',
            name='theme',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='forum_pages.subthemes'),
        ),
        migrations.AlterField(
            model_name='subthemes',
            name='base_theme',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='subthemes', to='forum_pages.themes'),
        ),
    ]
