# Generated by Django 4.1.4 on 2023-12-03 23:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('forum_pages', '0007_rename_thememessage_subthememessage_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='subthememessage',
            old_name='theme',
            new_name='subtheme',
        ),
    ]
