# Generated by Django 4.2.8 on 2024-01-22 18:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forum_pages', '0007_alter_maintextbanner_image_alter_topagency_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='maintextbanner',
            name='image',
            field=models.ImageField(upload_to='forum_pages/img/banners', verbose_name='Фото'),
        ),
    ]
