# Generated by Django 4.2.8 on 2024-02-04 21:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('forum_pages', '0011_basetheme'),
    ]

    operations = [
        migrations.RenameField(
            model_name='basetheme',
            old_name='accos',
            new_name='assoc',
        ),
    ]
