# Generated by Django 4.2.8 on 2024-02-04 22:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forum_pages', '0012_rename_accos_basetheme_assoc'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='basetheme',
            name='created2',
        ),
        migrations.AlterField(
            model_name='basetheme',
            name='created',
            field=models.DateField(auto_now_add=True),
        ),
    ]
