# Generated by Django 4.2.8 on 2024-04-01 23:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forum_pages', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='AgencyJobOrganization',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, verbose_name='Назва агенства')),
            ],
        ),
        migrations.AlterField(
            model_name='basetheme',
            name='text',
            field=models.TextField(verbose_name='Основний текст'),
        ),
        migrations.AlterField(
            model_name='basetheme',
            name='title',
            field=models.CharField(max_length=100, verbose_name='Заголовок'),
        ),
        migrations.AlterField(
            model_name='maintextbanner',
            name='link',
            field=models.URLField(verbose_name='Посилання'),
        ),
        migrations.AlterField(
            model_name='theme',
            name='title',
            field=models.CharField(max_length=100, null=True, verbose_name='Назва теми'),
        ),
    ]
