# Generated by Django 4.2.8 on 2024-04-20 14:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('forum_pages', '0003_basetheme_link'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='basetheme',
            name='link',
        ),
    ]
